gnetlist/tests/hierarchy: update and re-enable tests

diff --git a/gnetlist/tests/hierarchy/Makefile.am b/gnetlist/tests/hierarchy/Makefile.am
--- a/gnetlist/tests/hierarchy/Makefile.am
+++ b/gnetlist/tests/hierarchy/Makefile.am
@@ -2,11 +2,8 @@
 
 EXTRA_DIST = 1217.geda bottom.sch bottom.sym gnetlistrc.hierarchy gschemrc \
 	     gschlasrc hierarchy.geda middle.sch middle.sym rock.sch rock.sym \
-	     top.sch
+	     top.sch pnp-hierarchy.sym
 
-
-# Temporarily disabled make check, since this is interfering with
-# make distcheck
 check_SCRIPTS = tests
 
 BUILDDIR=$(top_builddir)/gnetlist/tests/hierarchy
@@ -15,9 +12,10 @@ GNETLIST=$(top_builddir)/gnetlist/src/gnetlist
 
 tests:
 
-notests:
-	rm -f $(BUILDDIR)/new_*
-	cp -f $(SRCDIR)/gnetlistrc.hierarchy $(BUILDDIR)/gnetlistrc
+# pre-clean
+	@rm -f $(BUILDDIR)/new_*
+# make and run the tests
+	@cp -f $(SRCDIR)/gnetlistrc.hierarchy $(BUILDDIR)/gnetlistrc
 	( TESTDIR=$(SRCDIR) \
 	  GEDADATARC=$(top_builddir)/gnetlist/lib \
 	  SCMDIR=${top_builddir}/gnetlist/scheme \
@@ -28,9 +26,17 @@ notests:
 	      -o $(BUILDDIR)/new_hierarchy.geda \
 	      -g geda $(SRCDIR)/top.sch )
 	diff $(SRCDIR)/hierarchy.geda $(BUILDDIR)/new_hierarchy.geda;
-	rm -f $(BUILDDIR)/gnetlistrc
+	@if test $$? -ne 0 ; then \
+		echo "FAILED: gnetlist/tests/hierarchy" ; \
+		cat $(BUILDDIR)/failed.log ; \
+		exit 1 ; \
+	else \
+		echo "PASSED: gnetlist/tests/hierarchy" ; \
+	fi
+	@rm -f $(BUILDDIR)/gnetlistrc
+	@rm -rf $(BUILDDIR)/logs
 
-MOSTLYCLEANFILES = new_* core *.log FILE *.ps *~ gnetlistrc
-CLEANFILES = new_* core *.log FILE *.ps *~ gnetlistrc
-DISTCLEANFILES = *.log core FILE *~ gnetlistrc
-MAINTAINERCLEANFILES = new_* core *.log FILE *.ps *~ Makefile.in gnetlistrc
+MOSTLYCLEANFILES     = new_* *.log *~ gnetlistrc pnp-test.sym
+CLEANFILES           = new_* *.log *~ gnetlistrc pnp-test.sym
+DISTCLEANFILES       = new_* *.log *~ gnetlistrc pnp-test.sym
+MAINTAINERCLEANFILES = new_* *.log *~ gnetlistrc pnp-test.sym Makefile.in
