Update/revise doxygen configurations, add config for toplevel

diff --git a/docs/Makefile.am b/docs/Makefile.am
--- a/docs/Makefile.am
+++ b/docs/Makefile.am
@@ -1,12 +1,52 @@
+SUBDIRS     = images symbols toplevel wiki scheme-api
 
-SUBDIRS    = symbols toplevel wiki scheme-api
+# These "extra" files are all for the Doxygen source documentation
+GEDA_EXTRA  = logo_256x101.png logo_512x208.png
 
-EXTRA_DIST = ChangeLog-1.0 ChangeLog
+LOCAL_DOX   = geda.dox geda-main.txt
+
+LOCAL_HTML  = what-is-geda.html
+
+LOCAL_TEX   = what-is-geda.tex
+
+LOCAL_EXTRA = ChangeLog-1.0 ChangeLog
+ 
+EXTRA_DIST  = $(GEDA_EXTRA) $(LOCAL_DOX) $(LOCAL_HTML) $(LOCAL_TEX) $(LOCAL_EXTRA)
 
 if HAVE_GIT_REPO
 ChangeLog: $(top_builddir)/stamp-git
 	(cd $(srcdir) && $(GIT) log --pretty=medium $(CHANGELOG_BASE).. -- .) > $@
 endif HAVE_GIT_REPO
+
+all: 
+	@echo 'Type: make doxygen  to create doxygen documentation for geda'
+
+# When generating doxygen documentation we check for the existence of the
+# output directory and create if needed. After doxygen executes, we check
+# for the latex directory is skip the latex if the diretory does not exist.
+doxygen:
+	@echo 'Creating doxygen documentation for geda...'
+if ENABLE_DOXYGEN
+	-(cd images && $(MAKE) images)
+	@if test "X@DOXYGEN_PATH_OUT@" != "X./" ; then \
+	    DOXYGEN_OUTDIR=@DOXYGEN_PATH_OUT@/geda; \
+	    test -d "$$DOXYGEN_OUTDIR" || $(MKDIR_P) "$$DOXYGEN_OUTDIR"; \
+	    export "DOXYGEN_OUTDIR=$$DOXYGEN_OUTDIR"; \
+	    $(DOXYGEN) geda.dox; \
+	    echo "Doxygen output generated in $$DOXYGEN_OUTDIR"; \
+	    test -d "$$DOXYGEN_OUTDIR"/latex && \
+	    (cd $$DOXYGEN_OUTDIR/latex && $(MAKE)) || : ; \
+	else \
+	    DOXYGEN_OUTDIR="./"; \
+	    $(DOXYGEN) geda.dox; \
+	    test -d latex && (cd latex && $(MAKE)) || : ;\
+	fi
+
+	-(cd ..)
+else
+	@echo 'configure was not run with the --enable-doxygen switch.'
+	@echo 'The documentation cannot be built from the sources.'
+endif
 
 MOSTLYCLEANFILES     = *.log core FILE *~
 CLEANFILES           = *.log core FILE *~
